// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXvqV42YPkfx4aLXrz6-joblNz_Jl9LfI',
    appId: '1:463573507763:web:2879f4fff78caa025e1ac6',
    messagingSenderId: '463573507763',
    projectId: 'flutter-test-42323',
    authDomain: 'flutter-test-42323.firebaseapp.com',
    storageBucket: 'flutter-test-42323.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAus3XBAPdZ_CyXvdIf1aGtG6YY60E0Ays',
    appId: '1:463573507763:android:c24d6899339364a65e1ac6',
    messagingSenderId: '463573507763',
    projectId: 'flutter-test-42323',
    storageBucket: 'flutter-test-42323.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOtlfavdO-VB9aqhjcvOk9sGg7ahNUR_0',
    appId: '1:463573507763:ios:d35634bd0f645c495e1ac6',
    messagingSenderId: '463573507763',
    projectId: 'flutter-test-42323',
    storageBucket: 'flutter-test-42323.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOtlfavdO-VB9aqhjcvOk9sGg7ahNUR_0',
    appId: '1:463573507763:ios:d35634bd0f645c495e1ac6',
    messagingSenderId: '463573507763',
    projectId: 'flutter-test-42323',
    storageBucket: 'flutter-test-42323.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );
}
